import type { Metadata } from "next";
import "./globals.css";

import { Abril_Fatface } from 'next/font/google';
 
const abril_fatface = Abril_Fatface({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-abril-fatface'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={abril_fatface.className}>{children}</body>
    </html>
  );
}
